
package ug.or.nda.services.configs;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.3-b02-
 * Generated source version: 2.0
 * 
 */
@WebServiceClient(name = "ConfigurationServiceService", targetNamespace = "http://services.nda.or.ug", wsdlLocation = "http://212.22.169.19/broker/config/v2.0?wsdl")
public class ConfigurationServiceService
    extends Service
{

    private final static URL CONFIGURATIONSERVICESERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(ConfigurationServiceService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = ConfigurationServiceService.class.getResource(".");
            url = new URL(baseUrl, "http://212.22.169.19/broker/config/v2.0?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://212.22.169.19/broker/config/v2.0?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        CONFIGURATIONSERVICESERVICE_WSDL_LOCATION = url;
    }

    public ConfigurationServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ConfigurationServiceService() {
        super(CONFIGURATIONSERVICESERVICE_WSDL_LOCATION, new QName("http://services.nda.or.ug", "ConfigurationServiceService"));
    }

    /**
     * 
     * @return
     *     returns Configs
     */
    @WebEndpoint(name = "ConfigsPort")
    public Configs getConfigsPort() {
        return super.getPort(new QName("http://services.nda.or.ug", "ConfigsPort"), Configs.class);
    }

}
