
package ug.or.nda.ws.client.payment;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

import ug.or.nda.dto.InvoiceDTO;
import ug.or.nda.dto.PaymentNotificationDTO;
import ug.or.nda.dto.PaymentNotificationRawLogDTO;
import ug.or.nda.dto.QueryDTO;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.3-b02-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "paymentQueryService", targetNamespace = "http://services.nda.or.ug")
public interface PaymentQueryService {
	
    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<ug.or.nda.service.InvoiceDTO>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listInvoices", targetNamespace = "http://services.nda.or.ug", className = "ug.or.nda.services.ListInvoices")
    @ResponseWrapper(localName = "listInvoicesResponse", targetNamespace = "http://services.nda.or.ug", className = "ug.or.nda.services.ListInvoicesResponse")
    public List<InvoiceDTO> listInvoices(
        @WebParam(name = "arg0", targetNamespace = "")
        QueryDTO arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<ug.or.nda.service.PaymentNotificationRawLogDTO>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listPaymentRawLogs", targetNamespace = "http://services.nda.or.ug", className = "ug.or.nda.services.ListPaymentRawLogs")
    @ResponseWrapper(localName = "listPaymentRawLogsResponse", targetNamespace = "http://services.nda.or.ug", className = "ug.or.nda.services.ListPaymentRawLogsResponse")
    public List<PaymentNotificationRawLogDTO> listPaymentRawLogs(
        @WebParam(name = "arg0", targetNamespace = "")
        QueryDTO arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<ug.or.nda.service.PaymentNotificationDTO>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listPayments", targetNamespace = "http://services.nda.or.ug", className = "ug.or.nda.services.ListPayments")
    @ResponseWrapper(localName = "listPaymentsResponse", targetNamespace = "http://services.nda.or.ug", className = "ug.or.nda.services.ListPaymentsResponse")
    public List<PaymentNotificationDTO> listPayments(
        @WebParam(name = "arg0", targetNamespace = "")
        QueryDTO arg0);

}
