
package ug.or.nda.ws.client.payment;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.3-b02-
 * Generated source version: 2.0
 * 
 */
@WebServiceClient(name = "PaymentQueryServiceService", targetNamespace = "http://services.nda.or.ug", wsdlLocation = "http://localhost:8080/broker/payment/query/v1.0?wsdl")
public class PaymentQueryServiceService
    extends Service
{

    private final static URL PAYMENTQUERYSERVICESERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(PaymentQueryServiceService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = PaymentQueryServiceService.class.getResource(".");
            url = new URL(baseUrl, "http://localhost:8080/broker/payment/query/v1.0?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://localhost:8080/broker/payment/query/v1.0?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        PAYMENTQUERYSERVICESERVICE_WSDL_LOCATION = url;
    }

    public PaymentQueryServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PaymentQueryServiceService() {
        super(PAYMENTQUERYSERVICESERVICE_WSDL_LOCATION, new QName("http://services.nda.or.ug", "PaymentQueryServiceService"));
    }

    /**
     * 
     * @return
     *     returns PaymentQueryService
     */
    @WebEndpoint(name = "paymentQueryServicePort")
    public PaymentQueryService getPaymentQueryServicePort() {
        return super.getPort(new QName("http://services.nda.or.ug", "paymentQueryServicePort"), PaymentQueryService.class);
    }

}
