
package ug.or.nda.ws.client.user;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.3-b02-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "userService", targetNamespace = "http://services.nda.or.ug")
public interface UserService {


    /**
     * 
     * @param arg0
     * @return
     *     returns ug.or.nda.services.UserDTO
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findUserByUsername", targetNamespace = "http://services.nda.or.ug", className = "ug.or.nda.services.FindUserByUsername")
    @ResponseWrapper(localName = "findUserByUsernameResponse", targetNamespace = "http://services.nda.or.ug", className = "ug.or.nda.services.FindUserByUsernameResponse")
    public UserDTO findUserByUsername(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
