
package ug.or.nda.ws.client.user;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.3-b02-
 * Generated source version: 2.0
 * 
 */
@WebServiceClient(name = "UserServiceService", targetNamespace = "http://services.nda.or.ug", wsdlLocation = "http://localhost:8080/broker/user/v1.0?wsdl")
public class UserServiceService
    extends Service
{

    private final static URL USERSERVICESERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(UserServiceService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = UserServiceService.class.getResource(".");
            url = new URL(baseUrl, "http://localhost:8080/broker/user/v1.0?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://localhost:8080/broker/user/v1.0?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        USERSERVICESERVICE_WSDL_LOCATION = url;
    }

    public UserServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public UserServiceService() {
        super(USERSERVICESERVICE_WSDL_LOCATION, new QName("http://services.nda.or.ug", "UserServiceService"));
    }

    /**
     * 
     * @return
     *     returns UserService
     */
    @WebEndpoint(name = "userServicePort")
    public UserService getUserServicePort() {
        return super.getPort(new QName("http://services.nda.or.ug", "userServicePort"), UserService.class);
    }

}
