
package ug.or.nda.ws.client.encryption;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.3-b02-
 * Generated source version: 2.0
 * 
 */
@WebServiceClient(name = "EncryptionServiceService", targetNamespace = "http://services.nda.or.ug", wsdlLocation = "http://localhost:8080/broker/encryption/v1.0?wsdl")
public class EncryptionServiceService
    extends Service
{

    private final static URL ENCRYPTIONSERVICESERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(EncryptionServiceService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = EncryptionServiceService.class.getResource(".");
            url = new URL(baseUrl, "http://localhost:8080/broker/encryption/v1.0?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://localhost:8080/broker/encryption/v1.0?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        ENCRYPTIONSERVICESERVICE_WSDL_LOCATION = url;
    }

    public EncryptionServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public EncryptionServiceService() {
        super(ENCRYPTIONSERVICESERVICE_WSDL_LOCATION, new QName("http://services.nda.or.ug", "EncryptionServiceService"));
    }

    /**
     * 
     * @return
     *     returns EncryptionService
     */
    @WebEndpoint(name = "encryptionServicePort")
    public EncryptionService getEncryptionServicePort() {
        return super.getPort(new QName("http://services.nda.or.ug", "encryptionServicePort"), EncryptionService.class);
    }

}
