
package ug.or.nda.ws.client.encryption;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.3-b02-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "encryptionService", targetNamespace = "http://services.nda.or.ug")
public interface EncryptionService {


    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "hashPassword", targetNamespace = "http://services.nda.or.ug", className = "ug.or.nda.services.HashPassword")
    @ResponseWrapper(localName = "hashPasswordResponse", targetNamespace = "http://services.nda.or.ug", className = "ug.or.nda.services.HashPasswordResponse")
    public String hashPassword(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

}
